name: Build‑and‑merge‑notebooks‑PDF

on:
  push:               # run on every push to any branch, any file
  workflow_dispatch:  # allow manual trigger from the Actions tab

jobs:
  pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install "nbconvert[webpdf]==7.16.6" pypdf==5.4.0
          # fetch the Chromium browser for nbconvert’s WebPDF exporter
          playwright install chromium

      - name: Convert every notebook to PDF
        run: |
          mkdir -p build/pdfs
          find . -type f -name '*.ipynb' -print0 |
            while IFS= read -r -d '' nb; do
              jupyter nbconvert "$nb" --to webpdf --output-dir build/pdfs
            done

      - name: Merge PDFs into a single file
        run: |
          python <<'PY'
          import pathlib
          from pypdf import PdfWriter

          pdf_dir = pathlib.Path('build/pdfs')
          writer = PdfWriter()

          for pdf_path in sorted(pdf_dir.glob('*.pdf')):
              writer.append(str(pdf_path))   # concatenate in alphabetical order

          out_file = pathlib.Path('build/all_notebooks_combined.pdf')
          out_file.parent.mkdir(parents=True, exist_ok=True)
          with out_file.open('wb') as fh:
              writer.write(fh)
          print(f'Created {out_file}')
          PY

      - name: Upload combined PDF
        uses: actions/upload-artifact@v4
        with:
          name: notebooks-pdf
          path: build/all_notebooks_combined.pdf
