name: compile-document

on:
  push:           # run on every push to default branch
  workflow_dispatch:  # allow manual trigger from the UI

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]   # add windows-latest or macos-latest if needed
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ---------- cache -------------
      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      # ---------- dependencies -------
      - name: Upgrade pip + build deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install nbconvert[webpdf]==7.16.6 pypdf==5.4.0

      # ---------- convert notebooks ---
      - name: Convert all notebooks to individual PDFs (webpdf template)
        shell: bash
        run: |
          mkdir -p build/pdfs
          find . -name "*.ipynb" -not -path "*/.ipynb_checkpoints/*" \
            | sort \
            | while read nb; do
                jupyter nbconvert "$nb" --to webpdf --template lab --output-dir build/pdfs
              done

      # ---------- merge ---------------
      - name: Merge PDFs respecting folder order
        run: |
          python scripts/merge_pdfs.py   # your existing Python that now uses PdfWriter

      # ---------- upload --------------
      - name: Upload final document
        uses: actions/upload-artifact@v4
        with:
          name: course-PDF
          path: build/merged_document.pdf
