name: Compile Notebooks to PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-24.04

    steps:
      # 1) Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Install Python and cache pip
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.x'
          cache: pip

      # 3) Install system packages for PDF conversion
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ghostscript \
            pandoc \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-extra

      # 4) Install Python libraries
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install \
            jupyter \
            matplotlib \
            scipy \
            scikit-rf \
            nbsphinx \
            sphinx_copybutton \
            sphinx_gallery

      # 5) Convert all .ipynb to PDF
      - name: Convert notebooks to PDFs
        run: |
          mkdir -p build
          find . -type f -name '*.ipynb' | sort | \
          while read -r nb; do
            out="build/${nb#./}"
            out="${out%.ipynb}.pdf"
            mkdir -p "$(dirname "$out")"
            echo "Converting $nb → $out"
            jupyter nbconvert "$nb" \
              --to pdf \
              --execute \
              --ExecutePreprocessor.timeout=600 \
              --output-dir="$(dirname "$out")"
          done

      # 6) Merge PDFs into single file
      - name: Merge PDFs
        run: |
          find build -type f -name '*.pdf' | sort \
            | xargs gs -dBATCH -dNOPAUSE -q \
                -sDEVICE=pdfwrite \
                -sOutputFile=all_notebooks.pdf

      # 7) Upload the final PDF artifact
      - name: Upload merged PDF
        uses: actions/upload-artifact@v4
        with:
          name: all-notebooks-pdf
          path: all_notebooks.pdf
